### ISSUE TITLE
Error with EvoDashboard 3.1.3

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/WelcomeHtmlBox-EvoDashboard-Plugin#1]
Receiving the following error dashboard using Evo 1.3.3 and EvoDashboard 3.1.3
Plugin no longer works. :(

![my evolution site evo cms manager](https://user-images.githubusercontent.com/6113504/28743571-baafc218-7444-11e7-815b-e78ff03d5889.png)

**Comment by risingisland** [comment]
Never mind, I didnt realize that "WelcomeLinksBox" took its place in the new version. Nice!

**Comment by Nicola1971** [comment]
i will update all other widget this weekend - need to move from onmanagerwelcomehome event to onmanagerwelcomeprerender
